### ISSUE TITLE
Switch to HiddenMarkovModels.jl dependency?

### ISSUE THREAD

**Issue by gdalle** [dmetivie/PeriodicHiddenMarkovModels.jl#5]
Hi @dmetivie,
Now that HiddenMarkovModels v0.4 is released, you should have everything you need to transition your dependency! Let me know if I can help

**Comment by dmetivie** [comment]
Thanks! This is done now (almost a copy of what you wrote in your [time dependent tutorial](https://gdalle.github.io/HiddenMarkovModels.jl/dev/examples/temporal/)). 
Now I will try to add “smooth versions” of the PeriodicHMM

**Comment by gdalle** [comment]
Awesome! How did you find the interface? You're probably the only one who actually used it.

**Comment by dmetivie** [comment]
It was very smooth ! You did most of the work. I really like that the control variable and observation can be arbitrary. I don't have much experience outside Distributions.jl, but I look forward to use more generic objects.  
+ implementing my "smooth PeriodicHMM" through your interface.
